(()=>{
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const courtContacts={
 'Padel Playy Brawijaya':{phone:'+62 823-4282-0090',whatsapp:'6282342820090',instagram:'padelplayy',status:'verified',source:'Direktori awal website'}
};
const searchUrl=(platform,name,city)=>`https://www.google.com/search?q=${encodeURIComponent(`${name} ${city} official ${platform}`)}`;
const mapsUrl=p=>`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.searchQuery||`${p.name}, ${p.city}, Indonesia`)}`;
const initials=n=>n.replace(/[^A-Za-z0-9 ]/g,' ').split(/\s+/).filter(Boolean).slice(0,3).map(x=>x[0]).join('').toUpperCase();
const precision=p=>p==='verified_address'?'Alamat jelas':p==='online_geocoded'?'Pin tersimpan':p==='name_search'?'Pencarian nama':'Titik kota';

function reportHtml(){return `
<div class="report-hero"><div><span class="report-kicker">HUT TNI KE-81 • PADEL NUSANTARA 81</span><h2>Laporan Strategis Turnamen Padel Nasional</h2><p>Kerangka tujuan, KPI, bukti pencapaian, dan status kesiapan untuk menjadikan event ini sebagai aset olahraga tahunan TNI.</p></div><div class="report-score"><b>81</b><span>lapangan sebagai sasaran simbolik nasional</span></div></div>
<div class="report-metrics"><div><b>8</b><span>Strategic Objectives</span></div><div><b>20+</b><span>Kota/Wilayah Target</span></div><div><b>810</b><span>Peserta Sasaran</span></div><div><b>3</b><span>Matra TNI</span></div></div>
<div class="section-title"><span class="num">SO</span> Strategic Objectives</div>
<div class="so-grid">
<article class="so-card core"><span>SO 1</span><h3>Turnamen Padel Terbesar di Indonesia</h3><p>Menjadi event dengan peserta, lapangan, kota, dan jangkauan nasional terbesar.</p></article>
<article class="so-card core"><span>SO 2</span><h3>Menjadi Event Tahunan TNI</h3><p>Ditetapkan sebagai agenda olahraga berkelanjutan dalam rangka HUT TNI.</p></article>
<article class="so-card core"><span>SO 3</span><h3>Platform Pengembangan Atlet Padel Nasional</h3><p>Menghubungkan kompetisi, coaching clinic, talent scouting, dan jalur pembinaan PBPI.</p></article>
<article class="so-card core"><span>SO 4</span><h3>Benchmark Event Olahraga Nasional</h3><p>Membangun standar baru untuk tata kelola, teknologi, keamanan, dokumentasi, dan pengalaman peserta.</p></article>
<article class="so-card core"><span>SO 5</span><h3>Memecahkan Rekor MURI</h3><p>Mencapai rekor terverifikasi melalui pertandingan serentak, jumlah lapangan, kota, atau peserta.</p></article>
<article class="so-card support"><span>SO 6</span><h3>Memperkuat Kedekatan TNI dan Masyarakat</h3><p>Menciptakan ruang interaksi positif antara prajurit, komunitas, keluarga, dan generasi muda.</p></article>
<article class="so-card support"><span>SO 7</span><h3>Memperluas Ekosistem Padel Nasional</h3><p>Mendorong pemerataan venue, komunitas, kompetisi, dan pembinaan di luar kota utama.</p></article>
<article class="so-card support"><span>SO 8</span><h3>Kolaborasi dan Keberlanjutan Event</h3><p>Membangun kemitraan nasional dan model pembiayaan yang sehat untuk penyelenggaraan tahunan.</p></article>
</div>
<div class="section-title"><span class="num">KPI</span> Rekomendasi KPI Strategis 2026</div>
<div class="kpi-note"><strong>Format pelaporan:</strong> setiap KPI wajib memiliki baseline, target, PIC, sumber bukti, frekuensi update, serta status Hijau, Kuning, atau Merah.</div>
<div class="table-wrap kpi-table-wrap"><table class="kpi-table"><thead><tr><th>SO</th><th>KPI Utama</th><th>Target 2026</th><th>Bukti Wajib</th><th>PIC Utama</th></tr></thead><tbody>
<tr><td><strong>SO 1</strong></td><td>Peserta; kota aktif; lapangan aktif; show-up rate</td><td><strong>≥810 peserta</strong><br>≥20 kota<br>≥81 lapangan<br>Show-up ≥85%</td><td>Database peserta, venue log, draw, attendance</td><td>Event Director + Registration</td></tr>
<tr><td><strong>SO 2</strong></td><td>Keterlibatan tiga matra; status kalender; pertumbuhan tahunan</td><td>AD, AL, AU aktif<br>Masuk kalender 2027<br>YoY peserta ≥20%</td><td>Surat/kalender, daftar satuan, laporan tahunan</td><td>Steering Committee TNI</td></tr>
<tr><td><strong>SO 3</strong></td><td>Database atlet; coaching clinic; talent scouting; rujukan pembinaan</td><td>≥1.000 profil atlet<br>≥20 clinic<br>≥100 atlet terpantau<br>≥50 rujukan PBPI</td><td>Profil atlet, assessment, rekomendasi pelatih</td><td>PBPI Technical Director</td></tr>
<tr><td><strong>SO 4</strong></td><td>Ketepatan jadwal; kepuasan; keselamatan; digitalisasi hasil</td><td>On-time ≥90%<br>Satisfaction ≥85%<br>Major incident 0<br>Digital result 100%</td><td>Match log, survey, incident log, result system</td><td>COO Event + Tournament Director</td></tr>
<tr><td><strong>SO 5</strong></td><td>Persetujuan konsep; skala rekor; kelengkapan bukti; sertifikasi</td><td>Konsep disetujui T-90<br>≥81 court / ≥20 kota<br>Bukti 100%<br>Sertifikat terbit</td><td>Surat MURI, video serentak, saksi, timestamp</td><td>MURI Lead + Documentation</td></tr>
<tr><td><strong>SO 6</strong></td><td>Partisipasi masyarakat; komunitas; sentimen publik</td><td>≥30% aktivitas publik<br>≥50 komunitas<br>Sentimen positif ≥85%</td><td>Registrasi, media monitoring, survey publik</td><td>Community & PR Lead</td></tr>
<tr><td><strong>SO 7</strong></td><td>Provinsi; venue partner; kota baru; koordinator daerah</td><td>≥15 provinsi<br>≥25 venue partner<br>≥5 kota baru<br>PIC regional 100%</td><td>MoU venue, daftar kota, struktur regional</td><td>Regional Operations</td></tr>
<tr><td><strong>SO 8</strong></td><td>Cakupan sponsor; pemenuhan benefit; renewal; kontrol biaya</td><td>Sponsor cover ≥70%<br>Benefit 100%<br>Renewal intent ≥60%<br>Variance ≤10%</td><td>Kontrak, proof of performance, budget report</td><td>Commercial Director + Finance</td></tr>
</tbody></table></div>
<div class="section-title"><span class="num">RAG</span> Status Eksekutif</div><div class="rag-grid"><article><i class="rag-dot green"></i><strong>Hijau</strong><p>Target aman, bukti lengkap, tidak ada hambatan kritis.</p></article><article><i class="rag-dot yellow"></i><strong>Kuning</strong><p>Ada risiko atau ketergantungan yang harus ditutup sebelum milestone.</p></article><article><i class="rag-dot red"></i><strong>Merah</strong><p>Target terancam atau bukti belum memenuhi standar verifikasi.</p></article></div>`}

function venueShell(){return `<div class="section-title"><span class="num">2</span> Direktori Court, Kontak & Sosial Media</div><p class="desc">Setiap court disajikan dalam bentuk thumbnail informasi. Data yang belum terverifikasi ditandai jelas dan tidak dianggap sebagai kontak resmi.</p><div class="venue-summary"><div><b id="venueTotal">0</b><span>Total court</span></div><div><b id="venueAddress">0</b><span>Alamat jelas</span></div><div><b id="venueContact">0</b><span>Kontak terverifikasi</span></div><div><b id="venueSocial">0</b><span>Sosmed terverifikasi</span></div></div><div class="venue-toolbar"><input id="venueSearch" type="search" placeholder="Cari court, kota, provinsi..."><select id="venueProvince"><option value="">Semua provinsi</option></select><select id="venueDataStatus"><option value="">Semua status data</option><option value="verified">Kontak/sosmed terverifikasi</option><option value="needs-verification">Perlu verifikasi</option></select></div><div class="venue-grid" id="venueGrid"></div><div class="note"><strong>Instagram embed-ready:</strong> posting publik akan tampil langsung saat URL post/reel resmi dimasukkan. Profil yang belum memiliki URL post tetap dilengkapi tombol Instagram, YouTube, TikTok, Facebook, dan Maps.</div>`}

function isVerified(meta){return meta.status==='verified'||Boolean(meta.phone||meta.instagram||meta.website)}
function renderVenues(){
 const grid=document.getElementById('venueGrid');if(!grid)return;
 const q=(document.getElementById('venueSearch')?.value||'').toLowerCase().trim(),prov=document.getElementById('venueProvince')?.value||'',status=document.getElementById('venueDataStatus')?.value||'';
 const all=NATIONAL_POINTS.filter(p=>p.category==='padel').map(p=>({...p,meta:courtContacts[p.name]||{}}));
 const shown=all.filter(c=>{const verified=isVerified(c.meta),hay=[c.name,c.city,c.province,c.address].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!prov||c.province===prov)&&(!status||(status==='verified'?verified:!verified))});
 grid.innerHTML=shown.map(c=>{const m=c.meta,verified=isVerified(m),ig=m.instagram?`https://instagram.com/${m.instagram}`:searchUrl('Instagram',c.name,c.city),yt=m.youtube||searchUrl('YouTube',c.name,c.city),tt=m.tiktok||searchUrl('TikTok',c.name,c.city),fb=m.facebook||searchUrl('Facebook',c.name,c.city),contact=m.phone||'Belum terverifikasi';return `<article class="venue-card"><div class="venue-thumb"><span class="venue-initials">${initials(c.name)}</span><span class="venue-city">${esc(c.city)} • ${esc(c.province)}</span></div><div class="venue-body"><div class="venue-title-row"><h3>${esc(c.name)}</h3><span class="data-status ${verified?'verified':'pending'}">${verified?'TERVERIFIKASI':'PERLU VERIFIKASI'}</span></div><p class="venue-address">📍 ${esc(c.address)}<br><small>Presisi: ${precision(c.precision)}</small></p><div class="venue-contact"><strong>Kontak:</strong> ${esc(contact)}<br><strong>Sumber:</strong> ${esc(m.source||'Perlu konfirmasi langsung ke venue')}</div><div class="venue-actions"><a class="maps" href="${mapsUrl(c)}" target="_blank" rel="noopener">Google Maps</a>${m.whatsapp?`<a class="wa" href="https://wa.me/${m.whatsapp}" target="_blank" rel="noopener">WhatsApp</a>`:''}<a class="ig" href="${ig}" target="_blank" rel="noopener">${m.instagram?'Instagram':'Cari Instagram'}</a><a class="yt" href="${yt}" target="_blank" rel="noopener">YouTube</a><a class="tiktok" href="${tt}" target="_blank" rel="noopener">TikTok</a><a class="facebook" href="${fb}" target="_blank" rel="noopener">Facebook</a>${m.website?`<a href="${m.website}" target="_blank" rel="noopener">Website</a>`:''}</div></div></article>`}).join('')||'<div class="note">Tidak ada court sesuai filter.</div>';
 document.getElementById('venueTotal').textContent=all.length;document.getElementById('venueAddress').textContent=all.filter(c=>['verified_address','online_geocoded'].includes(c.precision)).length;document.getElementById('venueContact').textContent=all.filter(c=>(c.meta||{}).phone).length;document.getElementById('venueSocial').textContent=all.filter(c=>(c.meta||{}).instagram).length;
}
function bootVenues(){const p=document.getElementById('venueProvince');if(!p||p.dataset.ready)return;const values=[...new Set(NATIONAL_POINTS.filter(x=>x.category==='padel').map(x=>x.province))].sort((a,b)=>a.localeCompare(b,'id'));p.innerHTML='<option value="">Semua provinsi</option>'+values.map(v=>`<option>${esc(v)}</option>`).join('');p.dataset.ready='1';['venueSearch','venueProvince','venueDataStatus'].forEach(id=>{const el=document.getElementById(id);el?.addEventListener(id==='venueSearch'?'input':'change',renderVenues)});renderVenues()}
function switchV3(id){document.querySelectorAll('.nav-tab,.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));document.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x.id===id));if(id==='peta')setTimeout(()=>{if(typeof bootNationalMap==='function')bootNationalMap();if(typeof nationalMap!=='undefined'&&nationalMap)nationalMap.invalidateSize()},80);if(id==='lapangan')setTimeout(bootVenues,10);window.scrollTo({top:0,behavior:'smooth'})}
function install(){
 document.title='Padel Sport Indonesia | Laporan Strategis & Direktori Nasional';
 const h=document.querySelector('.header');if(h){h.querySelector('h1').textContent='Padel Sport Indonesia';h.querySelector('p').textContent='Laporan Strategis • Venue • PBPI • TNI • Peta Nasional • Rekor MURI';const b=h.querySelector('.badge');if(b)b.textContent='Website Laporan • Update Juli 2026 • Mobile Friendly'}
 const first=document.querySelector('.section');const report=document.createElement('div');report.className='section active';report.id='report';report.innerHTML=reportHtml();first.parentNode.insertBefore(report,first);document.querySelectorAll('.section').forEach(s=>{if(s.id!=='report')s.classList.remove('active')});
 const venue=document.getElementById('lapangan');if(venue)venue.innerHTML=venueShell();
 const nav=document.getElementById('navTabs');if(nav)nav.innerHTML='<div class="nav-tab active" data-tab="report">1. Laporan Strategis</div><div class="nav-tab" data-tab="lapangan">2. Venue & Sosmed</div><div class="nav-tab" data-tab="peta">3. Peta Nasional</div><div class="nav-tab" data-tab="pengprov">4. Pengprov</div><div class="nav-tab" data-tab="kontak">5. Kontak</div><div class="nav-tab" data-tab="merk">6. Mitra</div><div class="nav-tab" data-tab="muri">7. Rekor MURI</div>';
 const bottom=document.querySelector('.bottom-nav');if(bottom)bottom.innerHTML='<button class="active" data-tab="report"><span class="icon">📊</span>Report</button><button data-tab="lapangan"><span class="icon">🏟️</span>Venue</button><button data-tab="peta"><span class="icon">🗺️</span>Peta</button><button data-tab="pengprov"><span class="icon">📋</span>PBPI</button><button data-tab="kontak"><span class="icon">📞</span>Kontak</button><button data-tab="muri"><span class="icon">🏅</span>MURI</button>';
 document.querySelectorAll('.nav-tab,.bottom-nav button').forEach(x=>x.addEventListener('click',()=>switchV3(x.dataset.tab)));
 const footer=document.querySelector('.footer');if(footer)footer.innerHTML='Padel Sport Indonesia • Website Laporan Strategis • Update Juli 2026<br>Data publik wajib diverifikasi sebelum digunakan.';
 bootVenues();switchV3('report');
}
try{install()}catch(err){console.error('Report v3 failed:',err)}
})();
